### ISSUE TITLE
How do you put Incap behind -experimental flag in Gradle?

### ISSUE THREAD

**Issue by gstevey** [gradle/incap#102]
Need instructions from Gradle team.

**Comment by stephanenicolas** [comment]
org.gradle.api.Incubating ?

**Comment by oehme** [comment]
You can add an incubating property to [CompileOptions](https://github.com/gradle/gradle/blob/master/subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/CompileOptions.java#L81)

**Comment by gstevey** [comment]
Fixed with next push.
