### ISSUE TITLE
Need JitPack to auto-update after pushes

### ISSUE THREAD

**Issue by gstevey** [gradle/incap#19]
For some reason, JitPack isn't picking up changes to master after a merged PR.  They're there on the JitPack page, and you can select them and get the code to copy in:

![image](https://user-images.githubusercontent.com/29737393/27756328-6c4b56c8-5dab-11e7-9f26-169c9b668773.png)

But I've found I have to change it to a different commit hash each time in order for gradle to download the latest version properly.

**Comment by oehme** [comment]
You can use SNAPSHOT as the version number.

**Comment by gstevey** [comment]
I was; it wasn't picking up my changes.  Need to dig into it some more.

**Comment by oehme** [comment]
Keep in mind the default timeout in Gradle is 24h.

**Comment by stephanenicolas** [comment]
I have added a policy to force the renewal of snapshots in the PR: 
https://github.com/gstevey/gradle/pull/2
