### ISSUE TITLE
Need mapping file version (in the file name)

### ISSUE THREAD

**Issue by gstevey** [gradle/incap#31]
Stefan pointed out that Gradle can be using a different version of incap from the AP(s), to allow incap to evolve independently of Gradle.

Hence, we need a file versioning scheme, though at this point I'm fuzzy on the details of what we'd actually do with the information.  I think it depends on whether we need backwards compatibility.

The Gradle folks would like the version number to be in the filename itself, to enable making decisions without needing to probe the file content.

**Comment by stephanenicolas** [comment]
This was adressed, we needed to change slightly the API: gradle is gonna to give incap a folder to write its mapping file. An incap will make sure the name of the mapping file conforms to this new rule.
