### ISSUE TITLE
Create integration tests in Gradle when gradle fork is ready

### ISSUE THREAD

**Issue by stephanenicolas** [gradle/incap#49]
We can get inspired / add a test to : 
https://github.com/melix/gradle/blob/9719201adef4c6ac449c16b6558a51dcef083d3c/subprojects/plugins/src/integTest/groovy/org/gradle/java/compile/IncrementalJavaCompileIntegrationTest.groovy

On line 59, then have a very similar test. By adding some annotation processing and modifying the base class, we can probably get a good test to check that an AP-dependency would be recompiled as well and an AP would produce the expected output.

**Comment by gstevey** [comment]
I have some new integration tests for M1, but not all of them are working properly, and I cannot figure out how to debug them.

Gradle is spinning up execution workers for the tests, and I need to be able to debug the relevant worker.

**Comment by gstevey** [comment]
This is done.
