### ISSUE TITLE
Make gradle support incremental annotation processing

### ISSUE THREAD

**Issue by stephanenicolas** [gradle/incap#50]
This issue is more about summarizing all the information from @melix about what has to be done on the gradle side. It doesn't mean we (@stevey , @wangwh03 ) have to tackle it but, at least, we have the information:

* Keep the modifications we have in IncrementalCompilerDecorator to perform incremental compilation when there are annotation processors. https://github.com/melix/gradle/blob/9719201adef4c6ac449c16b6558a51dcef083d3c/subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/IncrementalCompilerDecorator.java#L84-L84

* Change the recompile spec to take into account the stategraph: 
https://github.com/melix/gradle/blob/9719201adef4c6ac449c16b6558a51dcef083d3c/subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/RecompilationSpecProvider.java
Here, we could have something like a AnnotationProcessorChangeProcessor that would use the mapping file from incap to evaluate the AP-dependencies and add them to the list of files that gradle needs to recompile.

* The hard part is probably about serializing the state graph information, this will probably be done at the CompileCache level:
https://github.com/melix/gradle/blob/9719201adef4c6ac449c16b6558a51dcef083d3c/subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/cache/DefaultGeneralCompileCaches.java

**Comment by gstevey** [comment]
This has been addressed for M1.  Closing.
