### ISSUE TITLE
Rename modules

### ISSUE THREAD

**Issue by stephanenicolas** [gradle/incap#62]
Rename all modules so that they are prefix by 'incap':
* incap-ap-client
* incap-build-client
* incap-model (old core)
* incap-shared

Also, in the `settings.gradle` file, we could change the name of the root project:
```groovy
rootProject.name = 'incap'
```

We can also re-order the modules in the same file so that examples are last.

We don't need to rename the examples.

**Comment by wangwh03** [comment]
https://github.com/gradle/incap/pull/73

**Comment by wangwh03** [comment]
https://github.com/gradle/incap/pull/74

**Comment by stephanenicolas** [comment]
I reopen to make things more clear: folder and modules should match.
