### ISSUE TITLE
Create an IncrementalProcessingEnvironment class

### ISSUE THREAD

**Issue by stephanenicolas** [gradle/incap#68]
that will contain the logic of the BaseAnnotationProcessor class, and allow compisition over inheritance.

**Comment by oehme** [comment]
I adjusted the design doc - This is what I call `IncrementalProcessingEnvironment`, which has one method for wrapping the real processing environment and one method that gives you the supported options.

**Comment by tbroyer** [comment]
@oehme Is the design doc publicly available somewhere? At first glance, I find it strange that the annotation processor needs to be modified; except maybe to support the case where the Java compiler is not called through the JSR199 API?

**Comment by stephanenicolas** [comment]
Here is the document Thomas:
https://docs.google.com/document/d/1CXNfKmPx9hqfnGWic3F9sKHQ6T8ImDVxnXfkvWYqwxg/

JSR 199 is not enough to support incremental annotation processing.




2017-10-09 3:55 GMT-07:00 Thomas Broyer <notifications@github.com>:

**Comment by oehme** [comment]
@tbroyer if you have an idea how to intercept annotation processing through JSR 199, I'd be happy to hear it. What we need to do is recording the calls to the `Filer`.

**Comment by tbroyer** [comment]
I haven't read the design doc yet (thanks for the link), but if all you need is the `IncrementalJavaFiler`, then how about wrapping the `StandardJavaFiler` that you then pass to the `JavaCompiler`'s `getTask`? (all from within Gradle, no change in annotation processor side)

**Comment by oehme** [comment]
Maybe I'm missing something, but I think you mixed up `Filer` and `FileManager`

**Comment by tbroyer** [comment]
Absolutely :smiley: Was on phone, couldn't check things and totally mixed up APIs, sorry.

I have a vague memory of Pants doing something similar a few years back, though they were using jmake too and not just javac (and they now switched to using Zinc); that was mostly heuristics though IIRC.

It might be technically possible to actually have a unique incremental annotation processor that would somehow implement JSR 269: loading annotation processors using `ServiceLoader` in `init()`, and delegating all methods to them, except passing an `IncrementalFiler` (through an `IncrementalProcessingEnvironment`). Then call javac with `-processor org.gradle.incap.IncrementalAnnotationProcessor` to bypass discovery (would be done by the processor itself). Something like:

```java
class IncrementalAnnotationProcessor implements Processor {
  private IncrementalProcessingEnvironment processingEnv;
  private Iterable<Processor> processors;

  @Override
  public void init(ProcessingEnvironment processingEnv) {
    this.processingEnv = IncrementalProcessingEnvironment.create(processingEnv);
    // TODO: handle an equivalent to `-processor` through a `processingEnv.getOptions()`
    this.processors = ServiceLoader.load(Processor.class, getClass().getClassLoader());
    for (Processor processor : processors) {
      processor.init(this.processingEnv);
    }
  }

  @Override
  public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
    return processingEnv.record(() -> {
      for (Processor processor : processors) {
        // TODO: it would be necessary to track which processor has already been called,
        // and actually conditionally call the processor only if it has matching annotations,
        // or has already been called in a prior round.
        // TODO: actually cache getSupportedAnnotationTypes per processor,
        // as the Processor contract says they'll only be called once per run, not per round.
        boolean claimed = processor.process(filterAnnotations(annotations, processor.getSupportedAnnotationTypes()), roundEnv);

        // TODO: it would be necessary to track which annotations have been claimed,
        // which would influence filterAnnotations() above.
      }
      // We're supposed to be the only processor, so we an safely claim annotations.
      return true;
    });
  }

  /**
   * Returns a subset of the passed annotations matching the supported annotation types.
   *
   * TODO: handle claimed annotations as well.
   */
  private Set<? extends TypeElement> filterAnnotations(Set<? extends TypeElement> annotations, Set<String> supportedAnnotationTypes) {
    …
  }

  @Override
  public Set<String> getSupportedOptions() {
    Set<String> supportedOptions = new LinkedHashSet<>();
    // TODO: handle an equivalent to `-processor` through a `processingEnv.getOptions()`
    // supportedOptions.add("incap.processors");
    supportedOptions.add(MappingFileConstants.MAPPING_FILE_FOLDER_OPTION);
    for (Processor processor : processors) {
      supportedOptions.addAll(processor.getSupportedOptions());
    }
  }

  // Same for getSupportedAnnotationTypes(), except possibly process wildcards
  // or maybe as we're supposed to be the only processor, we can just return "*". 

  @Override
  public SourceVersion getSupportedSourceVersion() {
    SourceVersion ssv = SourceVersion.RELEASE_0;
    for (Processor processor : processors) {
      SourceVersion pssv = processor.getSupportedSourceVersion();
      if (pssv.compareTo(ssv) > 0) {
        ssv = pssv;
      }
    }
    return ssv;
  }

  @Override
  public Iterable<? extends Completion> getCompletions(Element element, AnnotationMirror annotation, ExecutableElement member, String userText) {
    throw new UnsupportedOperationException();
  }
}
```

Anyway, let's first tackle the hard work (actually processing annotations incrementally; unless you're already doing it?), then improve build integration.

BTW, `IncrementalProcessingEnvironment` exists in the source tree, should this issue be closed?

**Comment by oehme** [comment]
> Anyway, let's first tackle the hard work (actually processing annotations incrementally; unless you're already doing it?), then improve build integration.

Have a look at the design doc - it's actually all about integration into an existing incremental compiler. 

Wrapping the processors would be possible - we could also generate a single delegating wrapper around each one. 

The big problem are what we call "aggregating processors", which merge several annotated elements into a single output file. Take for instance a "service registry processor" listing all things annotated with `@Service` in a single output class. If you add a new `@Service`, there is no cheap way for the build system to tell that all other services need to be recompiled too. The build system would have to parse sources to find that out, which is expensive. So instead the approach will be to give annotation processors a way to find out which other files were an input to a given output file. The service registry processor could then discover all the other (unchanged) services on the classpath and correctly regenerate the full registry. This requires a change to the annotation processor anyway, so we didn't look much at approaches that don't change the processor.

If we had a way to directly hook into the round environment, we could of course automate this discovery, making the processor-facing API obsolete. But I'm not aware of such a hook in the compiler API.

You're right, this issue can be closed by now.

**Comment by tbroyer** [comment]
@oehme The "aggregating processors" use-case is very interesting. How about using a wrapping annotation processor (like I proposed above) that could detect those processors that use the API internally (e.g. they say they support the `incap.mapping.workdir` and/or `incap.incremental.enabled` options; or they implement a marker interface –many annotaition processors shade their dependencies, so that one marker interface would have to be kept unshaded, in a transitive dependency–, or have a specific annotation) so that they wouldn't be wrapped in the `incrementalProcessingEnvironment.record(…)` and would receive the original (non-wrapped) `ProcessingEnvironment`?

That way, incap would work with all existing processors with no change; and "aggregating processors" could make use of the incap APIs to handle incrementality themselves.
(I suppose that non-incremental aggregating processors would somehow be detected and disable incap entirely? or if not possible –imagine if there's only one `@Service` annotated class in the first run, the service registry processors looks like any other non-aggregating processor form the outside then– then incap would have to be explicitly enabled/disabled? unless I missed it, I didn't see anything about this in the design doc)
