### ISSUE TITLE
Remove `tools` folder

### ISSUE THREAD

**Issue by oehme** [gradle/incap#85]
The ruby scripts in there are unnecessary. Gradle has a really nice plugin for interacting with git repositories and for calling other Gradle builds. The purpose of `create-command` is not quite clear to me. It calls `gradle build` and then excludes a bunch of things. Instead of calling `build`, you can just call what you really want Gradle to do. I assume the intent was to call `gradle install` to create a local Gradle installation of a branch.

Also the steps in the readme are unnecessarily complicated. Some of them are unclear to me, e.g. `run gradle configuration step then kill gradle : ./gradlew clean build. The goal is to resolve all dependencies.`. Why do that? Just tell Gradle what you really wanted to do (again, probably `gradle install`) .

**Comment by stephanenicolas** [comment]
I will change the docs, I could use 
```bash
./gradlew install -Pgradle_installPath=~/gradle-source-build/
```
and it worked just fine, being much faster than the original script. Thx @oehme for looking into this. 

I don't issue a PR now as I couldn't test all things due to a permission issue on @gstevey repo. But soon !
