### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by oehme** [gradle/incap#87]
We'd like to build Incap on TeamCity. For now a simple `gradle check` in Linux and Windows should suffice.

**Comment by jjohannes** [comment]
I set up a TeamCity build for Linux and Windows. (The Windows one is currently failing.)

Everyone can access it via the guest login: https://builds.gradle.org/project.html?projectId=Incap

The configuration is stored on the separate branch [teamcity-versioned-settings](https://github.com/gradle/incap/tree/teamcity-versioned-settings).

I notice that there is also a Travis CI build configured. I don't know if we want to keep both.
