### ISSUE TITLE
Fix Gradle bug related to removal of generated files (or not?)

### ISSUE THREAD

**Issue by stephanenicolas** [gradle/incap#95]
This issue is to track the discussions about a bug currently in gradle that impacts the development of incap:

Current Gradle versions remove class files before incremental compilation (see `org.gradle.api.internal.file.delete.Deleter` and `org/gradle/api/internal/tasks/compile/incremental/IncrementalCompilationInitializer.java:57`).

The deletion works by pattern matching: org/gradle/api/internal/tasks/compile/incremental/IncrementalCompilationInitializer.java:61
All files prefixed by "class to delete " + "$.*.class" will be deleted

The problem is that it's a common practice for APs to generate a class `Foo$$SomeSuffix` when processing a class `Foo`. Although some APs now use `__` instead of `$$`, a majority of APs still use the dolar sign separator. 

Hence, when a class is modified, gradle already removes 1:1 generated files for most APs. 
This "bug" from Gradle is actually blurring M1 release of incap. M1 incap is all about adding dependencies to remove the generated files. (The dependencies are obtained via the incremental filer).

Will this bug be fixed ? 
It would make incap M1 's achievements more clear to AP developers.

**Comment by oehme** [comment]
There is currently no plan to fix this, though you are of course welcome to work on a pull request. The correct solution would be to track the source->target mapping when doing the incremental analysis at the end of compilation. Then on the next build this information could be used to determine precisely which classes to recompile. If no source information is present in the .class file, we'd fall back to the usual pattern matching.

I don't think this is a blocker for M1.

**Comment by stephanenicolas** [comment]
The source target mentioned by @oehme is: org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysisData.java:36

This should be a Map<String, Set<String>> to account for inner classes.
Right ?

**Comment by oehme** [comment]
There should be no map, a class file is generated from exactly one Java source file.

**Comment by stephanenicolas** [comment]
Isn't the bug caused by trying to eras inner classes as well ? That why I
suggested the 1:many data structure between source files and class files.


2017-10-19 2:26 GMT-07:00 Stefan Oehme <notifications@github.com>:

**Comment by oehme** [comment]
Sure, you can do it that way round as well. Then again, it doesn't really matter, we'll just recompile them anyway (this was fixed recently, by adding the inner classes to the recompile spec as well as to the delete spec). I think there are more important problems to tackle to get M1 out of the door.

**Comment by stephanenicolas** [comment]
Ok, I just wanted to document this bug properly as it is in the scope of M1. But I will close the issue if we don't wanna address it. Thx.
