### ISSUE TITLE
Gradle fork outputs twice the processorpath when compiling

### ISSUE THREAD

**Issue by stephanenicolas** [gradle/incap#96]
I thought it was a gradle bug, but no, it's really a incap's gradle fork bug issue:
processor path is added twice on the command line.

To repro:  `gradle --no-build-cache clean :app:compileDebugJavaWithJavac -d` on the new york times app.

**Comment by gstevey** [comment]
I'm unable to reproduce the bug.  The command gives me about 1600 lines of output, but I do not see the processor path anywhere.

Stepping through an incremental build in the debugger, this is the command line created by JavaCompilerArgumentsBuilder:

[-source
 1.7
 -target
 1.7
 -d
 /Users/stevey/src/NewYorkTimes/app/build/intermediates/classes/debug
 -encoding
 UTF-8
 -bootclasspath
 /Users/stevey/Library/Android/sdk/platforms/android-26/android.jar
 -g
 -sourcepath
 
 -processorpath
 /Users/stevey/.gradle/caches/modules-2/files-2.1/com.jakewharton/butterknife-compiler/9.0.0-INCAP-2/c036f4d771f522d319efc12177ff3978031df677/butterknife-compiler-9.0.0-INCAP-2.jar:/Users/stevey/.gradle/caches/modules-2/files-2.1/com.google.auto.value/auto-value/1.5-incap-2/a8c78c415a3e87f362992f23bdfe6252cff71388/auto-value-1.5-incap-2.jar:/Users/stevey/.gradle/caches/modules-2/files-2.1/org.gradle.incap/incap-ap-client/0.0.2/2ac9057581cd9bcc1054fc651d77fce80da02ff7/incap-ap-client-0.0.2.jar:/Users/stevey/.gradle/caches/modules-2/files-2.1/com.squareup/javapoet/1.9.0/ecc5cf9c221d55481163e773b24336db149e51/javapoet-1.9.0.jar:/Users/stevey/.gradle/caches/modules-2/files-2.1/com.jakewharton/butterknife-annotations/9.0.0-INCAP-2/5544575562b93483958fa4e2e97fd5a00c56c1a9/butterknife-annotations-9.0.0-INCAP-2.jar:/Users/stevey/.gradle/caches/modules-2/files-2.1/com.google.auto/auto-common/0.8/c6f7af0e57b9d69d81b05434ef9f3c5610d498c4/auto-common-0.8.jar:/Users/stevey/.gradle/caches/modules-2/files-2.1/org.gradle.incap/incap-mapping-file/0.0.2/d05f73b1467c2ee5f6db6916aef482623ac3c81f/incap-mapping-file-0.0.2.jar:/Users/stevey/.gradle/caches/modules-2/files-2.1/org.gradle.incap/incap-shared/0.0.2/44553355136ca4964bd0d9a97ace17eef7dd5f07/incap-shared-0.0.2.jar:/Users/stevey/.gradle/caches/modules-2/files-2.1/org.gradle.incap/incap-model/0.0.2/8b851eecb73d4adbc27aead1bb9815c2d67a4cf1/incap-model-0.0.2.jar:/Users/stevey/.gradle/caches/modules-2/files-2.1/com.android.support/support-annotations/26.0.1/e1bb32b12b25e2f78e6786059ca7ea878f8345e0/support-annotations-26.0.1.jar:/Users/stevey/.gradle/caches/modules-2/files-2.1/com.google.guava/guava/19.0/6ce200f6b23222af3d8abb6b6459e6c44f4bb0e9/guava-19.0.jar
 -Aincap.mapping.workdir=/Users/stevey/src/NewYorkTimes/app/build/intermediates/annotationProcessing
 -Aincap.incremental.enabled=true
 -XDuseUnsharedTable=true]

The path argument itself is not duplicated, and there are no duplicates in the path.

**Comment by stephanenicolas** [comment]
I reopen to check if I can repro.

**Comment by stephanenicolas** [comment]
Can't repro. Well done @gstevey
